name: Slack Notification for PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Get PR details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          
          # Extract requested reviewers
          REVIEWERS=$(echo "$response" | jq -r '.requested_reviewers | map(.login) | join(",")')
          echo "REVIEWERS=${REVIEWERS}" >> $GITHUB_ENV

      - name: Prepare Slack Message
        id: prepare_message
        run: |
          SLACK_USERS='{"arch1tek": "U07CKPA8C4B"}'
          REVIEWERS=${{ env.REVIEWERS }}
          
          SLACK_TAGS=""
          for REVIEWER in $(echo "$REVIEWERS" | tr ',' ' '); do
            SLACK_ID=$(echo "$SLACK_USERS" | jq -r --arg user "$REVIEWER" '.[$user]')
            if [[ "$SLACK_ID" != "null" ]]; then
              SLACK_TAGS+="<@$SLACK_ID> "
            fi
          done
          
          echo "SLACK_TAGS=${SLACK_TAGS}" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, pullRequest, author
          text: "A new pull request has been created with reviewers: ${{ env.SLACK_TAGS }}! :tada:"
          author_name: "PR Bot ⚡️"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
