name: Slack Notification for PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested

jobs:

  notify:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    get_email:
    runs-on: ubuntu-latest
    steps:
      - name: Get reviewer details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWER: ${{ github.event.requested_reviewer.login }}
        run: |
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/$REVIEWER")
          email=$(echo $response | jq -r .email)

          echo "Reviewer Email: $email"
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo, pullRequest, author
          text: "A new pull request has been created! :tada: <@U07CKPA8C4B>"
          author_name: "PR Bot ⚡️"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}